export function CourtMarkings({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 320 180"
      aria-hidden="true"
      focusable="false"
    >
      <rect
        x="8"
        y="8"
        width="304"
        height="164"
        fill="none"
        stroke="var(--line)"
        strokeWidth="3"
        rx="2"
      />
      <line
        x1="160"
        y1="8"
        x2="160"
        y2="172"
        stroke="var(--line)"
        strokeWidth="3"
      />
      <rect
        x="70"
        y="28"
        width="180"
        height="124"
        fill="none"
        stroke="var(--line)"
        strokeWidth="2.5"
      />
      <line
        x1="70"
        y1="90"
        x2="250"
        y2="90"
        stroke="var(--line)"
        strokeWidth="2.5"
      />
      <line
        x1="8"
        y1="90"
        x2="70"
        y2="90"
        stroke="var(--line)"
        strokeWidth="2"
        opacity="0.7"
      />
      <line
        x1="250"
        y1="90"
        x2="312"
        y2="90"
        stroke="var(--line)"
        strokeWidth="2"
        opacity="0.7"
      />
    </svg>
  );
}
